spring.application.name=Connectly_CM
server.port=8000

#for google
google.client-id=84613388155-un48eac3hk4uu62pdivvsk4q0om0vhdv.apps.googleusercontent.com
google.client-secret=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
google.client.scope=email,profile,https://www.googleapis.com/auth/gmail.send
google.client.redirect-uri=http://localhost:8000/login/oauth2/code/google



#spring.application.name=Connectly_CM
#server.port=8000
#
##for google
#google.client-id=84613388155-un48eac3hk4uu62pdivvsk4q0om0vhdv.apps.googleusercontent.com
#google.client-secret=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
#google.client.scope=email,profile,https://www.googleapis.com/auth/gmail.send
#google.client.redirect-uri=http://localhost:8000/login/gmailCallback

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://Hrithik0216:Hrithik0216@cluster0.m321jgb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0mongodb+srv://Hrithik0216:Hrithik0216@cluster0.m321jgb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0mongodb+srv://Hrithik0216:Hrithik0216@cluster0.m321jgb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=connectly

#Pipedrive Credentials
pipedrive.client.id=7ce255df35ae6eff
pipedrive.client.secret=1e6a9bd292d6ede153fbd6f220c4649c06a3dfb7
pipedrive.api.token=187206b66b65009d147a1670b9028bb0f587618c

#Encryption
local.paraphrase=hG7*knQ2!Lp9#rT4&vN6@wY8

#JwtUtils
jwt.secret=27db492b2b786841d4b899deb459d6fb9df0c247df59d648ab7c6d0054accb8b
jwt.expiration=86400000
